version: '3'
services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'development'
    volumes: 
      - "db_data:/var/lib/mysql"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./fromthepage:/fromthepage
      - ./scripts:/scripts
      - ./share:/share
    ports:
      - "3000:3000" # Rails Web
    links: 
      - mailcatcher
    depends_on:
      - db
  mailcatcher:
    image: zolweb/docker-mailcatcher:latest
    ports:
      - "1025:1025" 
      - "1080:1080"
volumes:
  db_data: # You need to create this first! docker volume create --label db_data docker-compose run -e "RAILS_ENV=test"